name: Cron and retrieve sinkaroid data

on:
  workflow_dispatch:
  schedule:
    - cron: "0 11 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
          fetch-depth: 0
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Fetch anime
        run: bun run ci/getAnime.ts
      - name: Fetch manga
        run: bun run ci/getManga.ts
      - name: Fetch game
        run: STEAM_API_KEY=${{ secrets.STEAM_API_KEY }} bun run ci/getGame.ts
      - name: Fetch repository
        run: bun run ci/getRepository.ts ${{ secrets.GH_TOKEN }}
      - name: Fetch repository SAS
        run: bun run ci/getRepositorySAS.ts ${{ secrets.GH_TOKEN }}
      - name: Run ESLint
        run: bun run lint
      - name: Commit files
        run: |
          git add .
          git diff --cached --quiet && exit 0
          GIT_AUTHOR_NAME="github-actions[bot]" GIT_AUTHOR_EMAIL="github-actions[bot]@users.noreply.github.com" GIT_COMMITTER_NAME="github-actions[bot]" GIT_COMMITTER_EMAIL="github-actions[bot]@users.noreply.github.com" git commit -m "chore: cron and auto-synchronized data"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          branch: master
